version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: nestdb
    volumes:
      - ./data:/vas/lib/postgresql/data
    ports:
      - 5499:5432