version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: luis
      POSTGRES_PASSWORD: luis04
      POSTGRES_DB: nestdb
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5499:5432"

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
